services:
  app:
    build:
      context: .
    container_name: brokerx_app
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - DATABASE_URL=root:root@tcp(db:3306)/brokerx?parseTime=true
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://app:8080/health"]
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: brokerx_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: brokerx_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: brokerx
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
