events {}

http {
  upstream go_backend {
    least_conn;  
    server brokerx:8080;
  }

  upstream go_backend_pprof {
    least_conn;  
    server brokerx:6060;
  }

  server {
    listen 80;
    location / {
      proxy_pass http://go_backend;
    }

    location /debug/pprof/ {
      proxy_pass http://go_backend_pprof/debug/pprof/;
    }
  }
}
