@startuml C4 Level 1
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title BrokerX - C4 Container Diagram

Person(client, "Client", "End user interacting via web browser")

System_Boundary(bx, "BrokerX System") {
  Container(nginx, "NGINX API Gateway", "NGINX", "Verifies and routes requests to the appropriate service")
  Container(frontend, "frontend-service", "Go server", "Serves static html javascript files and routes some requests from frontend to backend")
  Container(order, "order-service", "Go RESTful API", "Handles creating and fetching orders")
  Container(user, "user-service", "Go RESTful API", "Handles authentication and user registration")
  Container(portfolio, "portfolio-service", "Go API", "Handles balancing wallets and positions quantities")
  Container(market, "market-data-service", "Go RESTful API", "Returns market data like stock prices and instruments")
  Container(matching, "matching-service", "Go Application", "Handles order matching and returning orders to the order book")
  Container(notification, "notification-service", "Go Application", "Handles sending notifications to user")
  Container(matching, "matching-service", "Go Application", "Handles order matching and returning orders to the order book")
  ContainerDb(kafka, "Kafka Event Broker", "Kafka", "Handles delivering of events on multiple topics")
  ContainerDb(redis, "Redis storage", "Redis", "Stores orders temporarily for order matching")
  ContainerDb(db, "MySQL Database", "MySQL", "Stores users, wallets, orders, executions, positions persistently")
}

Rel(client, nginx, "Sends all requests through", "HTTP/REST")
Rel(nginx, frontend, "Routes requests to", "HTTP/REST")
Rel(frontend, portfolio, "Routes requests to", "HTTP/REST")
Rel(frontend, market, "Routes requests to", "HTTP/REST")
Rel(frontend, order, "Submit/view orders", "HTTP/REST")
Rel(frontend, user, "Routes login and register requests to", "HTTP/REST")
Rel(matching, redis, "Reads/writes", "RESP/TCP")
Rel(matching, redis, "")
Rel(user, db, "Reads/writes", "TCP/IP")
Rel(order, db, "Reads/writes", "TCP/IP")
Rel(portfolio, db, "Reads/writes", "TCP/IP")
Rel(portfolio, kafka, "Produces/Consumes Events to/from", "kafka binary/TCP")
Rel(kafka, portfolio, "")
Rel(matching, kafka, "Produces/Consumes Events to/from", "kafka binary/TCP")
Rel(kafka, matching, "")
Rel(order, kafka, "Produces/Consumes Events to/from", "kafka binary/TCP")
Rel(kafka, order, "")
Rel(notification, kafka, "Consumes Events from", "kafka binary/TCP")


@enduml
