@startuml
title BrokerX - Domain Model

class User {
  +userId: int
  +name: string
  +email: string
  +password: string
}

class Position {
  +available_quantity: int
  +reserved_quantity: int
}

class Wallet {
  +available_funds: int
  +reserved_funds: int
}

class Instrument {
  +symbol: string
  +name: string
  +tickSize: decimal
  +priceBandPercent: int
}

class Order {
  +orderId: int
  +type: enum {market, limit}
  +action: enum {buy, sell}
  +timing: enum {ioc, day}
  +quantity: int
  +remainingQty: int
  +unitPrice: decimal
  +status: enum {open, filled, partially_filled, cancelled}
}

class ExecutionRecord {
  +executionId: int
  +price: decimal
  +quantity: int
  +timestamp: datetime
}

class Price {
  +symbol: string
  +price: decimal
  +timestamp: datetime
}

' Relationships
User "1" --> "*" Position
User "1" --> "1" Wallet
Position "*" --> "1" Instrument
Order "*" <-- "1" User
Order "*" --> "1" Instrument
ExecutionRecord "*" --> "1" Order
Instrument "1" --> "*" Price

@enduml
