@startuml
title BrokerX - Deployment Diagram

node "ETS VM (Linux)" as VM {
  
  node "Self-hosted GitHub Actions Runner" as Runner {
    artifact "CI/CD Jobs" as CICD
  }

  node "Docker Engine" as Docker {
    node "NGINX API Gateway" as nginx {
      artifact "nginx.conf" as nginxconf
    }
    
    node "frontend-service Container" as frontend {
      artifact "Go API\n(frontend-service)" as faf
    }
    
    node "order-service Container" as order {
      artifact "Go API\n(order-service)" as oaf
    }
    
    node "portfolio-service Container" as portfolio {
      artifact "Go API\n(portfolio-service)" as paf
    }
    
    node "market-data-service Container" as market {
      artifact "Go API\n(market-data-service)" as mdaf
    }
    
    node "matching-service Container" as matching {
      artifact "Go App\n(matching-service)" as maf
    }

    node "notification-service Container" as matching {
      artifact "Go App\n(notification-service)" as maf
    }

    node "MySQL Container" as DB {
      database "MySQL Database\n(brokerx_db)" as MySQL
    }
    
    node "Redis Container" as redis {
      database "Redis Cache" as Redis
    }
    
    node "Kafka Container" as kafka {
      queue "OrderEvents"
      queue "NotificationEvents"
      queue "MatchingEvents"
      queue "PortfolioEvents"
    }
  }
}

' External systems
node "Client Machine" as ClientMachine {
    node "Web browser (Edge, Firefox, Chrome, Safari)" as browser {
        artifact "HTML pages\n(index.html, login.html,...)"
    }
}

node "Dev Machine" as DevMachine {
    node "IDE (VS Code, IntelliJ, ...)" as IDE {
        artifact "Golang source code\n(.go, .mod, .sum, ...)"
    }
}

' Relationships
DevMachine - VM : <<HTTP>>
ClientMachine -- VM : <<HTTP>>


@enduml
