@startuml order_state_diagram

state CreatingOrder {
    note as n1
        order-service
    end note
}

state ValidatingOrderCompliance {
    note as n1
        order-service
    end note
}

state ReservingQuantities {
    note as n1
        portfolio-service
    end note
}

state MatchingOrder {
    note as n1
        matching-service
    end note
}

state ConfirmingOrder {
    note as n1
        portfolio-service
    end note
}

state UpdatingOrder {
    note as n1
        order-service
    end note
}

state SendingNotification {
    note as n1
        notification-service
    end note
}

[*] --> CreatingOrder

CreatingOrder --> ValidatingOrderCompliance : OrderCreated
CreatingOrder --> UpdatingOrder : OrderCreatedFailed

ValidatingOrderCompliance --> ReservingQuantities : OrderCompliant
ValidatingOrderCompliance --> UpdatingOrder : OrderComplianceFailed

ReservingQuantities --> MatchingOrder : QuantitiesReserved
ReservingQuantities --> UpdatingOrder : ReservingQuantitiesFailed

MatchingOrder --> ConfirmingOrder : OrderMatched
MatchingOrder --> UpdatingOrder : OrderMatchingFailed

ConfirmingOrder --> UpdatingOrder : OrderConfirmationFailed
ConfirmingOrder --> UpdatingOrder : OrderConfirmed
UpdatingOrder --> MatchingOrder : OrderOpen

UpdatingOrder --> SendingNotification : OrderCompleted
SendingNotification --> [*] : SagaCompleted

@enduml
