@startuml
title BrokerX - Package level diagram

package "{service}" {
  package "core" as core {
    [All internal service (business logic)]
  }

  package "ports" as ports {
    [All external interfaces]
  }

  package "adapters" {
    package "dao" {
      [SQL repos and Redis access objects]
    }
    package "clients" {
      [Http clients for calling external service]
      [Kafka event producers]
    }
    package "handlers" {
      [Http handlers for request endpoints]
      [Kafka topic consumers and event handlers]
    }
  }

  package "models" {
    [Order]
    [OrderEvent]
    [MatchingEvent]
    [ClaimedCandidate]
    [OutboxRecord]
    [Instrument]
    [Position]
    [User]
    [Wallet]
    [ExecutionRecord]
  }
}

' Relationships
core -> models : uses
ports --> models : references
core --> ports : references
adapters --> ports : implements

@enduml

