@startuml all_use_cases
left to right direction

actor Client as C

rectangle BrokerX {
    together {
        usecase "UC-01\nSign up" as UC01
        usecase "UC-02\nLogin" as UC02 #palegreen
        usecase "UC-03\nAdd funds" as UC03
        usecase "UC-04\nView stock" as UC04
        usecase "UC-06\nModify order" as UC06
    }
    
    together {
        usecase "UC-08\nConfirm order and notify client" as UC08
        usecase "UC-05\nPlace order" as UC05 #palegreen
        usecase "UC-07\nFind match and execute order" as UC07 #palegreen
    }
}

actor "Payment Service" as PS
actor "Market Data Provider" as MDP

' Client interactions
C --> UC01
C --> UC02
C --> UC03
C --> UC04
C --> UC05
C --> UC06

' External services interactions
UC03 -- PS 
UC04 -- MDP

' Relationships between use cases
UC08 -- C
UC05 <. UC07 : <<extend>>
UC08 <. UC07 : <<include>>

@enduml
