@startuml
title UC-05 Place Order

participant "OrderService" as os
participant "TransactionManager" as tm
participant "OrderRepo" as or
participant "OutboxRepo" as obr
database "MySQL DB" as mysql

participant "OutboxDispatcher" as obd

participant "OrderCreatedHandler" as handler
participant "ComplianceService" as cs
participant "MarketDataService" as mds

queue "Kafka" as kafka

participant "OrderCompliantHandler" as handler2
participant "WalletRepo" as wr
participant "PositionRepo" as pr

-> os : HTTPOrderRequest
== Transaction start ==
os -> tm : err := Do(orderRepo, outboxRepo)
os -> or : err := Create(req.order)
or -> mysql : err := Create(order)
os -> obr : err := CreateOutboxEvent(OrderCreatedEvent)
obr -> mysql : err := Create(OrderCreatedEvent)
== Transaction end ==
<-- os : HTTPResponse

== Asynchronous (in Goroutine1) ==
obd -> obr : events := GetOutboxEvents()
obd -> kafka : SendEvents(events)

== Asynchronous (in Goroutine2) ==
->> handler : OrderCreatedEvent
handler -> cs : VerifyOrderCompliance(event.order)
cs -> mds : GetStockInstrument(order.symbol)
cs -> kafka : SendEvent(OrderCompliant)

== Asynchronous (in Goroutine3) ==
->> handler2 : OrderCompliantEvent
== Transaction start ==
handler2 -> wr : err := ReserveFunds(event.order)
handler2 -> pr : err := ReservePositionQty(event.order)
handler2 -> obr : err := CreateOutboxEvent(QuantitiesReservedEvent)
== Transaction end ==
@enduml
