@startuml
title UC-07 Matching & Execution

participant "OrderValidatedHandler" as handler
participant "MatchingEngine (core)" as MatchEngine
participant "OrderBook (ports)" as book
database "Redis" as redis
queue "Kafka" as kafka

== Asynchronous (in Matching Service) ==
->> handler : QuantitiesReservedEvent
handler -> MatchEngine : err := SubmitOrder(event.Order)
MatchEngine -> book : err, matches := FindMatches(order, limit)
book -> redis : err, matches := getMatchesAndPopScript.Run()
MatchEngine -> MatchEngine : UpdateOrders(order, matches)
MatchEngine -> kafka: OrderMatchedEvent


@enduml
