name: CI/CD Pipeline

on:
  push:
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    name: Lint, Build, Test, Coverage, Trivy Scans
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - user
          - order
          - portfolio
          - market-data
          - matching
    defaults:
      run:
        working-directory: backend/services/${{ matrix.service }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.9
          cache-dependency-path: backend/services/${{ matrix.service }}/go.sum

      - name: Go Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ./backend/services/${{ matrix.service }}

      - name: Build
        run: go build ./...
        working-directory: ./backend/services/${{ matrix.service }}

      # - name: Start tests dependencies
      #   run: |
      #     docker rm -f brokerx_test_db || true
      #     docker compose -f docker-compose.test.yml down -v || true
      #     docker compose -f docker-compose.test.yml up -d
      #   working-directory: .

      # - name: Wait for MySQL
      #   run: |
      #     for i in {1..30}; do
      #       if docker exec brokerx_test_db mysqladmin ping -h "127.0.0.1" --silent; then
      #         echo "MySQL is ready!"
      #         break
      #       fi
      #       echo "Waiting for MySQL..."
      #       sleep 2
      #     done

      # - name: Run Tests with Coverage
      #   run: |
      #     go test -coverprofile=coverage.out ./...
      #     go tool cover -func=coverage.out | tee coverage.txt
      #     coverage=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
      #     coverage_int=${coverage%.*}
      #     if [ "$coverage_int" -lt 0 ]; then
      #       echo "Code coverage ($coverage%) is below 0%"
      #       exit 1
      #     fi
      #   working-directory: ./backend/services/${{ matrix.service }}

      - name: Run Trivy on filesystem
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          severity: HIGH,CRITICAL
          exit-code: "1"
          ignore-unfixed: true
          scanners: vuln,secret

      - name: Build Docker image
        run: docker build -t brokerx-${{ matrix.service }}-service .
        working-directory: ./backend/services/${{ matrix.service }}

      - name: Run Trivy on Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: brokerx-${{ matrix.service }}-service
          severity: HIGH,CRITICAL
          exit-code: "1"
          ignore-unfixed: true
          scanners: vuln,secret
        env:
          TRIVY_SKIP_DB_UPDATE: true

      - name: Cleanup test containers
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down -v || true
          docker rm -f brokerx_test_db || true

  deploy:
    name: Deploy with Docker Compose
    runs-on: self-hosted
    needs: build-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy containers
        run: |
          docker compose down || true
          docker compose up -d --build

      - name: Docker image prune
        if: always()
        run: docker system prune -a --volumes -f
